const music_score_from = require("../../middleware/music_score_from/index");
exports.findUid = music_score_from.findUid;
exports.createAGradeForm = music_score_from.createAGradeForm;
exports.getGradeFormList = music_score_from.getGradeFormList;
exports.findFormId_list = music_score_from.findFormId_list;
exports.findFormId = music_score_from.findFormId;
exports.updateForm = music_score_from.updateForm;
exports.delForm = music_score_from.delForm;
exports.musicFormRecord = music_score_from.musicFormRecord;